Feat/authorization
bilousoleksandr/AppStoreConnect pull request #6
Opened 2024-06-23 10:32 UTC by olexkoval

Test implement authorization

2024-06-23 11:16 UTC, bilousoleksandr requested changes

2024-06-23 11:16 UTC, bilousoleksandr commented on Targets/AppStoreConnectUI/Sources/Authorization/AuthView.swift
> +            Button("Auth Private Key File") {
Let's use strings and keys for them? And use swiftgen from L10N target. 

Let's say it will be a key `authorization.button.private-key`

```suggestion
            Button("a") {
```

2024-06-23 11:16 UTC, bilousoleksandr commented on Targets/AppStoreConnectUI/Sources/Authorization/AuthView.swift
>                  AuthInputField(title: "Issuer ID", binding: $viewModel.issuerID)
Same here 

Let's say it will be a key `authorization.text-field.issuer-id`
```suggestion
                AuthInputField(title: "Issuer ID", binding: $viewModel.issuerID)
```

2024-06-23 11:16 UTC, bilousoleksandr commented on Targets/AppStoreConnectUI/Sources/Authorization/AuthView.swift
> +        self._viewModel = StateObject(wrappedValue: viewModel)
Better not to use, but t is okay right now )

```suggestion
        self._viewModel = StateObject(wrappedValue: viewModel)
```

2024-06-23 11:16 UTC, bilousoleksandr commented on Targets/AppStoreConnectAuth/Sources/AuthorizationService.swift
> +            print("Did fetch \(apps.count) apps")
DO we need it? 

```suggestion
```

2024-06-23 11:16 UTC, bilousoleksandr commented on Targets/AppStoreConnectAuth/Sources/AuthorizationService.swift
> +            let apps = try await apiProvider!.request(request).data
Let's avoid force unwrapping and use `get` to receive the value

```suggestion
            let apps = try await apiProvider.get().request(request).data
```

2024-06-23 11:16 UTC, bilousoleksandr commented on Targets/AppStoreConnectUI/Sources/Authorization/AuthView.swift
> +            })
This one should be inside viewModel

```suggestion
            .fileImporter(isPresented: $viewModel.isImporting,
                          allowedContentTypes: viewModel.allowedContentTypes,
                          onCompletion: { result in
                viewModel.someHandleFunction(result)
            })
```

2024-06-23 11:16 UTC, bilousoleksandr commented on Targets/AppStoreConnectUI/Sources/Authorization/AuthView.swift
> +                    await viewModel.authorize()
Let's make AsyncButton in DesignKit with async closure, so you can avoid using task inside the button

```suggestion
                    await viewModel.authorize()
```

2024-06-23 11:16 UTC, bilousoleksandr commented on Targets/AppStoreConnectUI/Sources/Authorization/AuthViewModel.swift
> +            print("\(error)")
We can add some kind of logger later, let's add static func or static enum logger and use it everywhere instead of prints? 

```suggestion
static func log(_ error: Error) {
print(error)
}

static func log(message: String) {
print(error)
}
            log(error)
```

2024-06-23 11:16 UTC, bilousoleksandr commented on Targets/AppStoreConnectUI/Sources/Authorization/AuthViewModel.swift
> +            print("\(error)")
Let's add into US state this alert? Right now it could be system alert above the window, so you could store simple error

```suggestion
authorizationAllert  = error
            print("\(error)")
```

2024-06-23 12:24 UTC, olexkoval commented on Targets/AppStoreConnectUI/Sources/Authorization/AuthView.swift
> +            Button("Auth Private Key File") {
improved

2024-06-23 12:24 UTC, olexkoval commented on Targets/AppStoreConnectUI/Sources/Authorization/AuthView.swift
>                  AuthInputField(title: "Issuer ID", binding: $viewModel.issuerID)
improved

2024-06-23 12:26 UTC, olexkoval commented on Targets/AppStoreConnectAuth/Sources/AuthorizationService.swift
> +            print("Did fetch \(apps.count) apps")
removed

2024-06-23 12:27 UTC, olexkoval commented on Targets/AppStoreConnectAuth/Sources/AuthorizationService.swift
> +            let apps = try await apiProvider!.request(request).data
Suggest that we do not need to keep apiProvider as a property of AuthorizationService, so removed and improved force unwrapping

2024-06-23 12:29 UTC, olexkoval commented on Targets/AppStoreConnectUI/Sources/Authorization/AuthView.swift
> +        self._viewModel = StateObject(wrappedValue: viewModel)
Please clarify how to awoid this and still keep ability to have this initializer with viewModel for swiftUI view?

2024-06-24 11:06 UTC, bilousoleksandr commented on Targets/AppStoreConnectUI/Sources/Authorization/AuthView.swift
> +        self._viewModel = StateObject(wrappedValue: viewModel)
Here is a good article about this, you can also look at the default autogenerated init for state object. Let's do the same, auto closure with viewModel.

https://medium.com/@mega-blog/shall-we-make-all-stateobject-properties-private-in-swiftui-a844c7b576c9

2025-04-07 19:27 UTC, closed without merging